// this is an auto-generated file
#define VERSIONINFO_VERSIONSTRING "1.0.1.0"
#define VERSIONINFO_MAJOR 1
#define VERSIONINFO_MINOR 0
#define VERSIONINFO_BUILD 1
#define VERSIONINFO_REVISION 0
#define VERSIONINFO_COPYRIGHT ""
#define VERSIONINFO_COMPANY ""
#define VERSIONINFO_PRODUCT "NHaml"
